openapi: 3.0.3
info:
  title: Teedy Microservice API Documentation
  description: |-
    This is the API documention for a Teedy microservice that predicts which applicants are more likely to succeed, helping the new graduate students admissions process.
  version: 1.0.11
tags:
  - name: train
    description: Train the model
  - name: predict
    description: Predict whether applicant is likely to succeed or not
  - name: wipe
    description: Remove the model
paths:
  /train:
    get:
      tags:
        - train
      summary: Train model
      description: Train model with historical dataset of student performance
      operationId: trainModel
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnMsg:
                    type: string
                    description: Return message after training model
                    example: 'Trained in 1 sec. Model training score: 70%'
        '400':
          description: Invalid status value
  /predict:
    post:
      tags:
        - predict
      summary: Predict whether applicant is likely to succeed or not
      description: Predicts whether an applicant, based on certain attributes, is likely to succeed or not
      operationId: predictApplicant
      parameters:
        - name: G1
          in: query
          description: Student's first period grade. For valid response try numbers with value >= 0 or <= 20. Other values will generate exceptions.
          required: true
          explode: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 20
        - name: G2
          in: query
          description: Student's second period grade. For valid response try numbers with value >= 0 or <= 20. Other values will generate exceptions.
          required: true
          explode: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 20
        - name: studytime
          in: query
          description: Student's weekly study time. For valid response try numbers with value >= 1 or <= 4. Other values will generate exceptions.
          required: true
          explode: true
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 4
        - name: failures
          in: query
          description: Student's number of past class failures. For valid response try numbers with value >= 1 or <= 4. Other values will generate exceptions.
          required: true
          explode: true
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 4
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnMsg:
                    type: string
                    description: Return message after predicting an applicant's likelihood of success
                    example: 'Applicant is likely to succeed.'
        '400':
          description: Invalid status value
  /wipe:
    get:
      tags:
        - wipe
      summary: Wipe model
      description: Wipe the trained model
      operationId: wipeModel
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnMsg:
                    type: string
                    description: Return message after wiping model
                    example: 'Model wiped'
        '400':
          description: Invalid status value
